// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Protocol.proto
// Protobuf C++ Version: 6.32.1

#ifndef Protocol_2eproto_2epb_2eh
#define Protocol_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Protocol_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Protocol_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_Protocol_2eproto;
}  // extern "C"
namespace Protocol {
enum PacketId : int;
extern const uint32_t PacketId_internal_data_[];
class C_Chat;
struct C_ChatDefaultTypeInternal;
extern C_ChatDefaultTypeInternal _C_Chat_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull C_Chat_class_data_;
class C_Login;
struct C_LoginDefaultTypeInternal;
extern C_LoginDefaultTypeInternal _C_Login_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull C_Login_class_data_;
class C_Move;
struct C_MoveDefaultTypeInternal;
extern C_MoveDefaultTypeInternal _C_Move_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull C_Move_class_data_;
class PlayerSnapshot;
struct PlayerSnapshotDefaultTypeInternal;
extern PlayerSnapshotDefaultTypeInternal _PlayerSnapshot_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PlayerSnapshot_class_data_;
class S_Login;
struct S_LoginDefaultTypeInternal;
extern S_LoginDefaultTypeInternal _S_Login_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull S_Login_class_data_;
class S_StateSnapshot;
struct S_StateSnapshotDefaultTypeInternal;
extern S_StateSnapshotDefaultTypeInternal _S_StateSnapshot_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull S_StateSnapshot_class_data_;
class Vector2;
struct Vector2DefaultTypeInternal;
extern Vector2DefaultTypeInternal _Vector2_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Vector2_class_data_;
}  // namespace Protocol
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::Protocol::PacketId_internal_data_>
    internal::EnumTraitsImpl::value<::Protocol::PacketId>;
}  // namespace protobuf
}  // namespace google

namespace Protocol {
enum PacketId : int {
  PACKET_NONE = 0,
  C_LOGIN = 1,
  S_LOGIN = 2,
  C_MOVE = 3,
  S_MOVE = 4,
  C_CHAT = 5,
  S_CHAT = 6,
  S_STATE_SNAPSHOT = 7,
  PacketId_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  PacketId_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t PacketId_internal_data_[];
inline constexpr PacketId PacketId_MIN =
    static_cast<PacketId>(0);
inline constexpr PacketId PacketId_MAX =
    static_cast<PacketId>(7);
inline bool PacketId_IsValid(int value) {
  return 0 <= value && value <= 7;
}
inline constexpr int PacketId_ARRAYSIZE = 7 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL PacketId_descriptor();
template <typename T>
const ::std::string& PacketId_Name(T value) {
  static_assert(::std::is_same<T, PacketId>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to PacketId_Name().");
  return PacketId_Name(static_cast<PacketId>(value));
}
template <>
inline const ::std::string& PacketId_Name(PacketId value) {
  return ::google::protobuf::internal::NameOfDenseEnum<PacketId_descriptor, 0, 7>(
      static_cast<int>(value));
}
inline bool PacketId_Parse(
    ::absl::string_view name, PacketId* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<PacketId>(PacketId_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class Vector2 final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.Vector2) */ {
 public:
  inline Vector2() : Vector2(nullptr) {}
  ~Vector2() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Vector2* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Vector2));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Vector2(::google::protobuf::internal::ConstantInitialized);

  inline Vector2(const Vector2& from) : Vector2(nullptr, from) {}
  inline Vector2(Vector2&& from) noexcept
      : Vector2(nullptr, ::std::move(from)) {}
  inline Vector2& operator=(const Vector2& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vector2& operator=(Vector2&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Vector2& default_instance() {
    return *reinterpret_cast<const Vector2*>(
        &_Vector2_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Vector2& a, Vector2& b) { a.Swap(&b); }
  inline void Swap(Vector2* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vector2* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Vector2* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Vector2>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Vector2& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Vector2& from) { Vector2::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Vector2* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.Vector2"; }

 protected:
  explicit Vector2(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Vector2(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Vector2& from);
  Vector2(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Vector2&& from) noexcept
      : Vector2(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // float x = 1;
  void clear_x() ;
  float x() const;
  void set_x(float value);

  private:
  float _internal_x() const;
  void _internal_set_x(float value);

  public:
  // float y = 2;
  void clear_y() ;
  float y() const;
  void set_y(float value);

  private:
  float _internal_y() const;
  void _internal_set_y(float value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.Vector2)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Vector2& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    float x_;
    float y_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Vector2_class_data_;
// -------------------------------------------------------------------

class S_Login final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.S_Login) */ {
 public:
  inline S_Login() : S_Login(nullptr) {}
  ~S_Login() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(S_Login* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(S_Login));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR S_Login(::google::protobuf::internal::ConstantInitialized);

  inline S_Login(const S_Login& from) : S_Login(nullptr, from) {}
  inline S_Login(S_Login&& from) noexcept
      : S_Login(nullptr, ::std::move(from)) {}
  inline S_Login& operator=(const S_Login& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_Login& operator=(S_Login&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_Login& default_instance() {
    return *reinterpret_cast<const S_Login*>(
        &_S_Login_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(S_Login& a, S_Login& b) { a.Swap(&b); }
  inline void Swap(S_Login* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_Login* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_Login* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<S_Login>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const S_Login& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const S_Login& from) { S_Login::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(S_Login* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.S_Login"; }

 protected:
  explicit S_Login(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  S_Login(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const S_Login& from);
  S_Login(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, S_Login&& from) noexcept
      : S_Login(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNicknameFieldNumber = 3,
    kPlayerIdFieldNumber = 2,
    kLoginOkFieldNumber = 1,
  };
  // string nickname = 3;
  void clear_nickname() ;
  const ::std::string& nickname() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_nickname(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_nickname();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_nickname();
  void set_allocated_nickname(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_nickname() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_nickname(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_nickname();

  public:
  // uint64 player_id = 2;
  void clear_player_id() ;
  ::uint64_t player_id() const;
  void set_player_id(::uint64_t value);

  private:
  ::uint64_t _internal_player_id() const;
  void _internal_set_player_id(::uint64_t value);

  public:
  // bool login_ok = 1;
  void clear_login_ok() ;
  bool login_ok() const;
  void set_login_ok(bool value);

  private:
  bool _internal_login_ok() const;
  void _internal_set_login_ok(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.S_Login)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 33,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const S_Login& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr nickname_;
    ::uint64_t player_id_;
    bool login_ok_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull S_Login_class_data_;
// -------------------------------------------------------------------

class C_Login final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.C_Login) */ {
 public:
  inline C_Login() : C_Login(nullptr) {}
  ~C_Login() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(C_Login* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(C_Login));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR C_Login(::google::protobuf::internal::ConstantInitialized);

  inline C_Login(const C_Login& from) : C_Login(nullptr, from) {}
  inline C_Login(C_Login&& from) noexcept
      : C_Login(nullptr, ::std::move(from)) {}
  inline C_Login& operator=(const C_Login& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_Login& operator=(C_Login&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_Login& default_instance() {
    return *reinterpret_cast<const C_Login*>(
        &_C_Login_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(C_Login& a, C_Login& b) { a.Swap(&b); }
  inline void Swap(C_Login* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_Login* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_Login* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<C_Login>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const C_Login& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const C_Login& from) { C_Login::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(C_Login* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.C_Login"; }

 protected:
  explicit C_Login(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  C_Login(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const C_Login& from);
  C_Login(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, C_Login&& from) noexcept
      : C_Login(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUniqueIdFieldNumber = 1,
  };
  // string unique_id = 1;
  void clear_unique_id() ;
  const ::std::string& unique_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_unique_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_unique_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_unique_id();
  void set_allocated_unique_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_unique_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_unique_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_unique_id();

  public:
  // @@protoc_insertion_point(class_scope:Protocol.C_Login)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 34,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const C_Login& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr unique_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull C_Login_class_data_;
// -------------------------------------------------------------------

class C_Chat final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.C_Chat) */ {
 public:
  inline C_Chat() : C_Chat(nullptr) {}
  ~C_Chat() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(C_Chat* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(C_Chat));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR C_Chat(::google::protobuf::internal::ConstantInitialized);

  inline C_Chat(const C_Chat& from) : C_Chat(nullptr, from) {}
  inline C_Chat(C_Chat&& from) noexcept
      : C_Chat(nullptr, ::std::move(from)) {}
  inline C_Chat& operator=(const C_Chat& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_Chat& operator=(C_Chat&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_Chat& default_instance() {
    return *reinterpret_cast<const C_Chat*>(
        &_C_Chat_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(C_Chat& a, C_Chat& b) { a.Swap(&b); }
  inline void Swap(C_Chat* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_Chat* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_Chat* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<C_Chat>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const C_Chat& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const C_Chat& from) { C_Chat::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(C_Chat* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.C_Chat"; }

 protected:
  explicit C_Chat(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  C_Chat(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const C_Chat& from);
  C_Chat(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, C_Chat&& from) noexcept
      : C_Chat(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUsernameFieldNumber = 1,
    kMessageFieldNumber = 2,
  };
  // string username = 1;
  void clear_username() ;
  const ::std::string& username() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_username(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_username();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_username();
  void set_allocated_username(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_username() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_username(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_username();

  public:
  // string message = 2;
  void clear_message() ;
  const ::std::string& message() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_message();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_message();
  void set_allocated_message(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_message() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_message(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_message();

  public:
  // @@protoc_insertion_point(class_scope:Protocol.C_Chat)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 39,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const C_Chat& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr username_;
    ::google::protobuf::internal::ArenaStringPtr message_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull C_Chat_class_data_;
// -------------------------------------------------------------------

class PlayerSnapshot final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.PlayerSnapshot) */ {
 public:
  inline PlayerSnapshot() : PlayerSnapshot(nullptr) {}
  ~PlayerSnapshot() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PlayerSnapshot* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PlayerSnapshot));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PlayerSnapshot(::google::protobuf::internal::ConstantInitialized);

  inline PlayerSnapshot(const PlayerSnapshot& from) : PlayerSnapshot(nullptr, from) {}
  inline PlayerSnapshot(PlayerSnapshot&& from) noexcept
      : PlayerSnapshot(nullptr, ::std::move(from)) {}
  inline PlayerSnapshot& operator=(const PlayerSnapshot& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerSnapshot& operator=(PlayerSnapshot&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerSnapshot& default_instance() {
    return *reinterpret_cast<const PlayerSnapshot*>(
        &_PlayerSnapshot_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(PlayerSnapshot& a, PlayerSnapshot& b) { a.Swap(&b); }
  inline void Swap(PlayerSnapshot* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerSnapshot* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerSnapshot* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PlayerSnapshot>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PlayerSnapshot& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PlayerSnapshot& from) { PlayerSnapshot::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PlayerSnapshot* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.PlayerSnapshot"; }

 protected:
  explicit PlayerSnapshot(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PlayerSnapshot(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PlayerSnapshot& from);
  PlayerSnapshot(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PlayerSnapshot&& from) noexcept
      : PlayerSnapshot(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAuthoritativePositionFieldNumber = 2,
    kSessionIdFieldNumber = 1,
  };
  // .Protocol.Vector2 authoritative_position = 2;
  bool has_authoritative_position() const;
  void clear_authoritative_position() ;
  const ::Protocol::Vector2& authoritative_position() const;
  [[nodiscard]] ::Protocol::Vector2* PROTOBUF_NULLABLE release_authoritative_position();
  ::Protocol::Vector2* PROTOBUF_NONNULL mutable_authoritative_position();
  void set_allocated_authoritative_position(::Protocol::Vector2* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_authoritative_position(::Protocol::Vector2* PROTOBUF_NULLABLE value);
  ::Protocol::Vector2* PROTOBUF_NULLABLE unsafe_arena_release_authoritative_position();

  private:
  const ::Protocol::Vector2& _internal_authoritative_position() const;
  ::Protocol::Vector2* PROTOBUF_NONNULL _internal_mutable_authoritative_position();

  public:
  // uint32 session_id = 1;
  void clear_session_id() ;
  ::uint32_t session_id() const;
  void set_session_id(::uint32_t value);

  private:
  ::uint32_t _internal_session_id() const;
  void _internal_set_session_id(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.PlayerSnapshot)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PlayerSnapshot& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::Protocol::Vector2* PROTOBUF_NULLABLE authoritative_position_;
    ::uint32_t session_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PlayerSnapshot_class_data_;
// -------------------------------------------------------------------

class C_Move final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.C_Move) */ {
 public:
  inline C_Move() : C_Move(nullptr) {}
  ~C_Move() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(C_Move* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(C_Move));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR C_Move(::google::protobuf::internal::ConstantInitialized);

  inline C_Move(const C_Move& from) : C_Move(nullptr, from) {}
  inline C_Move(C_Move&& from) noexcept
      : C_Move(nullptr, ::std::move(from)) {}
  inline C_Move& operator=(const C_Move& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_Move& operator=(C_Move&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_Move& default_instance() {
    return *reinterpret_cast<const C_Move*>(
        &_C_Move_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(C_Move& a, C_Move& b) { a.Swap(&b); }
  inline void Swap(C_Move* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_Move* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_Move* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<C_Move>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const C_Move& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const C_Move& from) { C_Move::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(C_Move* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.C_Move"; }

 protected:
  explicit C_Move(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  C_Move(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const C_Move& from);
  C_Move(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, C_Move&& from) noexcept
      : C_Move(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDesiredVelocityFieldNumber = 1,
  };
  // .Protocol.Vector2 desired_velocity = 1;
  bool has_desired_velocity() const;
  void clear_desired_velocity() ;
  const ::Protocol::Vector2& desired_velocity() const;
  [[nodiscard]] ::Protocol::Vector2* PROTOBUF_NULLABLE release_desired_velocity();
  ::Protocol::Vector2* PROTOBUF_NONNULL mutable_desired_velocity();
  void set_allocated_desired_velocity(::Protocol::Vector2* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_desired_velocity(::Protocol::Vector2* PROTOBUF_NULLABLE value);
  ::Protocol::Vector2* PROTOBUF_NULLABLE unsafe_arena_release_desired_velocity();

  private:
  const ::Protocol::Vector2& _internal_desired_velocity() const;
  ::Protocol::Vector2* PROTOBUF_NONNULL _internal_mutable_desired_velocity();

  public:
  // @@protoc_insertion_point(class_scope:Protocol.C_Move)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const C_Move& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::Protocol::Vector2* PROTOBUF_NULLABLE desired_velocity_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull C_Move_class_data_;
// -------------------------------------------------------------------

class S_StateSnapshot final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.S_StateSnapshot) */ {
 public:
  inline S_StateSnapshot() : S_StateSnapshot(nullptr) {}
  ~S_StateSnapshot() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(S_StateSnapshot* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(S_StateSnapshot));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR S_StateSnapshot(::google::protobuf::internal::ConstantInitialized);

  inline S_StateSnapshot(const S_StateSnapshot& from) : S_StateSnapshot(nullptr, from) {}
  inline S_StateSnapshot(S_StateSnapshot&& from) noexcept
      : S_StateSnapshot(nullptr, ::std::move(from)) {}
  inline S_StateSnapshot& operator=(const S_StateSnapshot& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_StateSnapshot& operator=(S_StateSnapshot&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_StateSnapshot& default_instance() {
    return *reinterpret_cast<const S_StateSnapshot*>(
        &_S_StateSnapshot_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 6;
  friend void swap(S_StateSnapshot& a, S_StateSnapshot& b) { a.Swap(&b); }
  inline void Swap(S_StateSnapshot* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_StateSnapshot* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_StateSnapshot* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<S_StateSnapshot>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const S_StateSnapshot& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const S_StateSnapshot& from) { S_StateSnapshot::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(S_StateSnapshot* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.S_StateSnapshot"; }

 protected:
  explicit S_StateSnapshot(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  S_StateSnapshot(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const S_StateSnapshot& from);
  S_StateSnapshot(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, S_StateSnapshot&& from) noexcept
      : S_StateSnapshot(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPlayersFieldNumber = 2,
    kServerTickFieldNumber = 1,
  };
  // repeated .Protocol.PlayerSnapshot players = 2;
  int players_size() const;
  private:
  int _internal_players_size() const;

  public:
  void clear_players() ;
  ::Protocol::PlayerSnapshot* PROTOBUF_NONNULL mutable_players(int index);
  ::google::protobuf::RepeatedPtrField<::Protocol::PlayerSnapshot>* PROTOBUF_NONNULL mutable_players();

  private:
  const ::google::protobuf::RepeatedPtrField<::Protocol::PlayerSnapshot>& _internal_players() const;
  ::google::protobuf::RepeatedPtrField<::Protocol::PlayerSnapshot>* PROTOBUF_NONNULL _internal_mutable_players();
  public:
  const ::Protocol::PlayerSnapshot& players(int index) const;
  ::Protocol::PlayerSnapshot* PROTOBUF_NONNULL add_players();
  const ::google::protobuf::RepeatedPtrField<::Protocol::PlayerSnapshot>& players() const;
  // uint32 server_tick = 1;
  void clear_server_tick() ;
  ::uint32_t server_tick() const;
  void set_server_tick(::uint32_t value);

  private:
  ::uint32_t _internal_server_tick() const;
  void _internal_set_server_tick(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.S_StateSnapshot)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const S_StateSnapshot& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::Protocol::PlayerSnapshot > players_;
    ::uint32_t server_tick_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull S_StateSnapshot_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Vector2

// float x = 1;
inline void Vector2::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline float Vector2::x() const {
  // @@protoc_insertion_point(field_get:Protocol.Vector2.x)
  return _internal_x();
}
inline void Vector2::set_x(float value) {
  _internal_set_x(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:Protocol.Vector2.x)
}
inline float Vector2::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void Vector2::_internal_set_x(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// float y = 2;
inline void Vector2::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline float Vector2::y() const {
  // @@protoc_insertion_point(field_get:Protocol.Vector2.y)
  return _internal_y();
}
inline void Vector2::set_y(float value) {
  _internal_set_y(value);
  _impl_._has_bits_[0] |= 0x00000002U;
  // @@protoc_insertion_point(field_set:Protocol.Vector2.y)
}
inline float Vector2::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void Vector2::_internal_set_y(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// -------------------------------------------------------------------

// C_Login

// string unique_id = 1;
inline void C_Login::clear_unique_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.unique_id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& C_Login::unique_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.C_Login.unique_id)
  return _internal_unique_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void C_Login::set_unique_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.unique_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.C_Login.unique_id)
}
inline ::std::string* PROTOBUF_NONNULL C_Login::mutable_unique_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_unique_id();
  // @@protoc_insertion_point(field_mutable:Protocol.C_Login.unique_id)
  return _s;
}
inline const ::std::string& C_Login::_internal_unique_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.unique_id_.Get();
}
inline void C_Login::_internal_set_unique_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.unique_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL C_Login::_internal_mutable_unique_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.unique_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE C_Login::release_unique_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.C_Login.unique_id)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.unique_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.unique_id_.Set("", GetArena());
  }
  return released;
}
inline void C_Login::set_allocated_unique_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.unique_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.unique_id_.IsDefault()) {
    _impl_.unique_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_Login.unique_id)
}

// -------------------------------------------------------------------

// S_Login

// bool login_ok = 1;
inline void S_Login::clear_login_ok() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.login_ok_ = false;
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline bool S_Login::login_ok() const {
  // @@protoc_insertion_point(field_get:Protocol.S_Login.login_ok)
  return _internal_login_ok();
}
inline void S_Login::set_login_ok(bool value) {
  _internal_set_login_ok(value);
  _impl_._has_bits_[0] |= 0x00000004U;
  // @@protoc_insertion_point(field_set:Protocol.S_Login.login_ok)
}
inline bool S_Login::_internal_login_ok() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.login_ok_;
}
inline void S_Login::_internal_set_login_ok(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.login_ok_ = value;
}

// uint64 player_id = 2;
inline void S_Login::clear_player_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.player_id_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline ::uint64_t S_Login::player_id() const {
  // @@protoc_insertion_point(field_get:Protocol.S_Login.player_id)
  return _internal_player_id();
}
inline void S_Login::set_player_id(::uint64_t value) {
  _internal_set_player_id(value);
  _impl_._has_bits_[0] |= 0x00000002U;
  // @@protoc_insertion_point(field_set:Protocol.S_Login.player_id)
}
inline ::uint64_t S_Login::_internal_player_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.player_id_;
}
inline void S_Login::_internal_set_player_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.player_id_ = value;
}

// string nickname = 3;
inline void S_Login::clear_nickname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nickname_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& S_Login::nickname() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.S_Login.nickname)
  return _internal_nickname();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void S_Login::set_nickname(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.nickname_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.S_Login.nickname)
}
inline ::std::string* PROTOBUF_NONNULL S_Login::mutable_nickname()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_nickname();
  // @@protoc_insertion_point(field_mutable:Protocol.S_Login.nickname)
  return _s;
}
inline const ::std::string& S_Login::_internal_nickname() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nickname_.Get();
}
inline void S_Login::_internal_set_nickname(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.nickname_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL S_Login::_internal_mutable_nickname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.nickname_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE S_Login::release_nickname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.S_Login.nickname)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.nickname_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.nickname_.Set("", GetArena());
  }
  return released;
}
inline void S_Login::set_allocated_nickname(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.nickname_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.nickname_.IsDefault()) {
    _impl_.nickname_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.S_Login.nickname)
}

// -------------------------------------------------------------------

// C_Move

// .Protocol.Vector2 desired_velocity = 1;
inline bool C_Move::has_desired_velocity() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  PROTOBUF_ASSUME(!value || _impl_.desired_velocity_ != nullptr);
  return value;
}
inline void C_Move::clear_desired_velocity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.desired_velocity_ != nullptr) _impl_.desired_velocity_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::Protocol::Vector2& C_Move::_internal_desired_velocity() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Protocol::Vector2* p = _impl_.desired_velocity_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Vector2&>(::Protocol::_Vector2_default_instance_);
}
inline const ::Protocol::Vector2& C_Move::desired_velocity() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.C_Move.desired_velocity)
  return _internal_desired_velocity();
}
inline void C_Move::unsafe_arena_set_allocated_desired_velocity(
    ::Protocol::Vector2* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.desired_velocity_);
  }
  _impl_.desired_velocity_ = reinterpret_cast<::Protocol::Vector2*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.C_Move.desired_velocity)
}
inline ::Protocol::Vector2* PROTOBUF_NULLABLE C_Move::release_desired_velocity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001U;
  ::Protocol::Vector2* released = _impl_.desired_velocity_;
  _impl_.desired_velocity_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Protocol::Vector2* PROTOBUF_NULLABLE C_Move::unsafe_arena_release_desired_velocity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.C_Move.desired_velocity)

  _impl_._has_bits_[0] &= ~0x00000001U;
  ::Protocol::Vector2* temp = _impl_.desired_velocity_;
  _impl_.desired_velocity_ = nullptr;
  return temp;
}
inline ::Protocol::Vector2* PROTOBUF_NONNULL C_Move::_internal_mutable_desired_velocity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.desired_velocity_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Protocol::Vector2>(GetArena());
    _impl_.desired_velocity_ = reinterpret_cast<::Protocol::Vector2*>(p);
  }
  return _impl_.desired_velocity_;
}
inline ::Protocol::Vector2* PROTOBUF_NONNULL C_Move::mutable_desired_velocity()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001U;
  ::Protocol::Vector2* _msg = _internal_mutable_desired_velocity();
  // @@protoc_insertion_point(field_mutable:Protocol.C_Move.desired_velocity)
  return _msg;
}
inline void C_Move::set_allocated_desired_velocity(::Protocol::Vector2* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.desired_velocity_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }

  _impl_.desired_velocity_ = reinterpret_cast<::Protocol::Vector2*>(value);
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_Move.desired_velocity)
}

// -------------------------------------------------------------------

// C_Chat

// string username = 1;
inline void C_Chat::clear_username() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.username_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& C_Chat::username() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.C_Chat.username)
  return _internal_username();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void C_Chat::set_username(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.username_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.C_Chat.username)
}
inline ::std::string* PROTOBUF_NONNULL C_Chat::mutable_username()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_username();
  // @@protoc_insertion_point(field_mutable:Protocol.C_Chat.username)
  return _s;
}
inline const ::std::string& C_Chat::_internal_username() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.username_.Get();
}
inline void C_Chat::_internal_set_username(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.username_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL C_Chat::_internal_mutable_username() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.username_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE C_Chat::release_username() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.C_Chat.username)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.username_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.username_.Set("", GetArena());
  }
  return released;
}
inline void C_Chat::set_allocated_username(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.username_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.username_.IsDefault()) {
    _impl_.username_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_Chat.username)
}

// string message = 2;
inline void C_Chat::clear_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline const ::std::string& C_Chat::message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.C_Chat.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void C_Chat::set_message(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.C_Chat.message)
}
inline ::std::string* PROTOBUF_NONNULL C_Chat::mutable_message()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:Protocol.C_Chat.message)
  return _s;
}
inline const ::std::string& C_Chat::_internal_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_.Get();
}
inline void C_Chat::_internal_set_message(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.message_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL C_Chat::_internal_mutable_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  return _impl_.message_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE C_Chat::release_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.C_Chat.message)
  if ((_impl_._has_bits_[0] & 0x00000002U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002U;
  auto* released = _impl_.message_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.message_.Set("", GetArena());
  }
  return released;
}
inline void C_Chat::set_allocated_message(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002U;
  }
  _impl_.message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_Chat.message)
}

// -------------------------------------------------------------------

// PlayerSnapshot

// uint32 session_id = 1;
inline void PlayerSnapshot::clear_session_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_id_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline ::uint32_t PlayerSnapshot::session_id() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerSnapshot.session_id)
  return _internal_session_id();
}
inline void PlayerSnapshot::set_session_id(::uint32_t value) {
  _internal_set_session_id(value);
  _impl_._has_bits_[0] |= 0x00000002U;
  // @@protoc_insertion_point(field_set:Protocol.PlayerSnapshot.session_id)
}
inline ::uint32_t PlayerSnapshot::_internal_session_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.session_id_;
}
inline void PlayerSnapshot::_internal_set_session_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_id_ = value;
}

// .Protocol.Vector2 authoritative_position = 2;
inline bool PlayerSnapshot::has_authoritative_position() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  PROTOBUF_ASSUME(!value || _impl_.authoritative_position_ != nullptr);
  return value;
}
inline void PlayerSnapshot::clear_authoritative_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.authoritative_position_ != nullptr) _impl_.authoritative_position_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::Protocol::Vector2& PlayerSnapshot::_internal_authoritative_position() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Protocol::Vector2* p = _impl_.authoritative_position_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Vector2&>(::Protocol::_Vector2_default_instance_);
}
inline const ::Protocol::Vector2& PlayerSnapshot::authoritative_position() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.PlayerSnapshot.authoritative_position)
  return _internal_authoritative_position();
}
inline void PlayerSnapshot::unsafe_arena_set_allocated_authoritative_position(
    ::Protocol::Vector2* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.authoritative_position_);
  }
  _impl_.authoritative_position_ = reinterpret_cast<::Protocol::Vector2*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.PlayerSnapshot.authoritative_position)
}
inline ::Protocol::Vector2* PROTOBUF_NULLABLE PlayerSnapshot::release_authoritative_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001U;
  ::Protocol::Vector2* released = _impl_.authoritative_position_;
  _impl_.authoritative_position_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Protocol::Vector2* PROTOBUF_NULLABLE PlayerSnapshot::unsafe_arena_release_authoritative_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.PlayerSnapshot.authoritative_position)

  _impl_._has_bits_[0] &= ~0x00000001U;
  ::Protocol::Vector2* temp = _impl_.authoritative_position_;
  _impl_.authoritative_position_ = nullptr;
  return temp;
}
inline ::Protocol::Vector2* PROTOBUF_NONNULL PlayerSnapshot::_internal_mutable_authoritative_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.authoritative_position_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Protocol::Vector2>(GetArena());
    _impl_.authoritative_position_ = reinterpret_cast<::Protocol::Vector2*>(p);
  }
  return _impl_.authoritative_position_;
}
inline ::Protocol::Vector2* PROTOBUF_NONNULL PlayerSnapshot::mutable_authoritative_position()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001U;
  ::Protocol::Vector2* _msg = _internal_mutable_authoritative_position();
  // @@protoc_insertion_point(field_mutable:Protocol.PlayerSnapshot.authoritative_position)
  return _msg;
}
inline void PlayerSnapshot::set_allocated_authoritative_position(::Protocol::Vector2* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.authoritative_position_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }

  _impl_.authoritative_position_ = reinterpret_cast<::Protocol::Vector2*>(value);
  // @@protoc_insertion_point(field_set_allocated:Protocol.PlayerSnapshot.authoritative_position)
}

// -------------------------------------------------------------------

// S_StateSnapshot

// uint32 server_tick = 1;
inline void S_StateSnapshot::clear_server_tick() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_tick_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline ::uint32_t S_StateSnapshot::server_tick() const {
  // @@protoc_insertion_point(field_get:Protocol.S_StateSnapshot.server_tick)
  return _internal_server_tick();
}
inline void S_StateSnapshot::set_server_tick(::uint32_t value) {
  _internal_set_server_tick(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:Protocol.S_StateSnapshot.server_tick)
}
inline ::uint32_t S_StateSnapshot::_internal_server_tick() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.server_tick_;
}
inline void S_StateSnapshot::_internal_set_server_tick(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_tick_ = value;
}

// repeated .Protocol.PlayerSnapshot players = 2;
inline int S_StateSnapshot::_internal_players_size() const {
  return _internal_players().size();
}
inline int S_StateSnapshot::players_size() const {
  return _internal_players_size();
}
inline void S_StateSnapshot::clear_players() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.players_.Clear();
}
inline ::Protocol::PlayerSnapshot* PROTOBUF_NONNULL S_StateSnapshot::mutable_players(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Protocol.S_StateSnapshot.players)
  return _internal_mutable_players()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Protocol::PlayerSnapshot>* PROTOBUF_NONNULL S_StateSnapshot::mutable_players()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_StateSnapshot.players)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_players();
}
inline const ::Protocol::PlayerSnapshot& S_StateSnapshot::players(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.S_StateSnapshot.players)
  return _internal_players().Get(index);
}
inline ::Protocol::PlayerSnapshot* PROTOBUF_NONNULL S_StateSnapshot::add_players()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::Protocol::PlayerSnapshot* _add = _internal_mutable_players()->Add();
  // @@protoc_insertion_point(field_add:Protocol.S_StateSnapshot.players)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Protocol::PlayerSnapshot>& S_StateSnapshot::players() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Protocol.S_StateSnapshot.players)
  return _internal_players();
}
inline const ::google::protobuf::RepeatedPtrField<::Protocol::PlayerSnapshot>&
S_StateSnapshot::_internal_players() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.players_;
}
inline ::google::protobuf::RepeatedPtrField<::Protocol::PlayerSnapshot>* PROTOBUF_NONNULL
S_StateSnapshot::_internal_mutable_players() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.players_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::Protocol::PacketId> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::Protocol::PacketId>() {
  return ::Protocol::PacketId_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Protocol_2eproto_2epb_2eh
