// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Protocol.proto
// Protobuf C++ Version: 6.32.1

#ifndef Protocol_2eproto_2epb_2eh
#define Protocol_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Protocol_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Protocol_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_Protocol_2eproto;
}  // extern "C"
enum PacketId : int;
extern const uint32_t PacketId_internal_data_[];
class C_Login;
struct C_LoginDefaultTypeInternal;
extern C_LoginDefaultTypeInternal _C_Login_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull C_Login_class_data_;
class S_Login;
struct S_LoginDefaultTypeInternal;
extern S_LoginDefaultTypeInternal _S_Login_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull S_Login_class_data_;
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::PacketId_internal_data_>
    internal::EnumTraitsImpl::value<::PacketId>;
}  // namespace protobuf
}  // namespace google

enum PacketId : int {
  PACKET_NONE = 0,
  C_LOGIN = 1,
  S_LOGIN = 2,
  C_MOVE = 3,
  S_MOVE = 4,
  PacketId_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  PacketId_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t PacketId_internal_data_[];
inline constexpr PacketId PacketId_MIN =
    static_cast<PacketId>(0);
inline constexpr PacketId PacketId_MAX =
    static_cast<PacketId>(4);
inline bool PacketId_IsValid(int value) {
  return 0 <= value && value <= 4;
}
inline constexpr int PacketId_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL PacketId_descriptor();
template <typename T>
const ::std::string& PacketId_Name(T value) {
  static_assert(::std::is_same<T, PacketId>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to PacketId_Name().");
  return PacketId_Name(static_cast<PacketId>(value));
}
template <>
inline const ::std::string& PacketId_Name(PacketId value) {
  return ::google::protobuf::internal::NameOfDenseEnum<PacketId_descriptor, 0, 4>(
      static_cast<int>(value));
}
inline bool PacketId_Parse(
    ::absl::string_view name, PacketId* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<PacketId>(PacketId_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class S_Login final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:S_Login) */ {
 public:
  inline S_Login() : S_Login(nullptr) {}
  ~S_Login() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(S_Login* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(S_Login));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR S_Login(::google::protobuf::internal::ConstantInitialized);

  inline S_Login(const S_Login& from) : S_Login(nullptr, from) {}
  inline S_Login(S_Login&& from) noexcept
      : S_Login(nullptr, ::std::move(from)) {}
  inline S_Login& operator=(const S_Login& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_Login& operator=(S_Login&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_Login& default_instance() {
    return *reinterpret_cast<const S_Login*>(
        &_S_Login_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(S_Login& a, S_Login& b) { a.Swap(&b); }
  inline void Swap(S_Login* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_Login* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_Login* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<S_Login>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const S_Login& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const S_Login& from) { S_Login::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(S_Login* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "S_Login"; }

 protected:
  explicit S_Login(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  S_Login(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const S_Login& from);
  S_Login(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, S_Login&& from) noexcept
      : S_Login(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNicknameFieldNumber = 3,
    kPlayerIdFieldNumber = 2,
    kLoginOkFieldNumber = 1,
  };
  // string nickname = 3;
  void clear_nickname() ;
  const ::std::string& nickname() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_nickname(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_nickname();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_nickname();
  void set_allocated_nickname(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_nickname() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_nickname(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_nickname();

  public:
  // uint64 player_id = 2;
  void clear_player_id() ;
  ::uint64_t player_id() const;
  void set_player_id(::uint64_t value);

  private:
  ::uint64_t _internal_player_id() const;
  void _internal_set_player_id(::uint64_t value);

  public:
  // bool login_ok = 1;
  void clear_login_ok() ;
  bool login_ok() const;
  void set_login_ok(bool value);

  private:
  bool _internal_login_ok() const;
  void _internal_set_login_ok(bool value);

  public:
  // @@protoc_insertion_point(class_scope:S_Login)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 24,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const S_Login& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr nickname_;
    ::uint64_t player_id_;
    bool login_ok_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull S_Login_class_data_;
// -------------------------------------------------------------------

class C_Login final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:C_Login) */ {
 public:
  inline C_Login() : C_Login(nullptr) {}
  ~C_Login() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(C_Login* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(C_Login));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR C_Login(::google::protobuf::internal::ConstantInitialized);

  inline C_Login(const C_Login& from) : C_Login(nullptr, from) {}
  inline C_Login(C_Login&& from) noexcept
      : C_Login(nullptr, ::std::move(from)) {}
  inline C_Login& operator=(const C_Login& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_Login& operator=(C_Login&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_Login& default_instance() {
    return *reinterpret_cast<const C_Login*>(
        &_C_Login_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(C_Login& a, C_Login& b) { a.Swap(&b); }
  inline void Swap(C_Login* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_Login* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_Login* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<C_Login>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const C_Login& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const C_Login& from) { C_Login::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(C_Login* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "C_Login"; }

 protected:
  explicit C_Login(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  C_Login(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const C_Login& from);
  C_Login(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, C_Login&& from) noexcept
      : C_Login(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUniqueIdFieldNumber = 1,
  };
  // string unique_id = 1;
  void clear_unique_id() ;
  const ::std::string& unique_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_unique_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_unique_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_unique_id();
  void set_allocated_unique_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_unique_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_unique_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_unique_id();

  public:
  // @@protoc_insertion_point(class_scope:C_Login)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 25,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const C_Login& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr unique_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull C_Login_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// C_Login

// string unique_id = 1;
inline void C_Login::clear_unique_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.unique_id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& C_Login::unique_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:C_Login.unique_id)
  return _internal_unique_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void C_Login::set_unique_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.unique_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:C_Login.unique_id)
}
inline ::std::string* PROTOBUF_NONNULL C_Login::mutable_unique_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_unique_id();
  // @@protoc_insertion_point(field_mutable:C_Login.unique_id)
  return _s;
}
inline const ::std::string& C_Login::_internal_unique_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.unique_id_.Get();
}
inline void C_Login::_internal_set_unique_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.unique_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL C_Login::_internal_mutable_unique_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.unique_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE C_Login::release_unique_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:C_Login.unique_id)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.unique_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.unique_id_.Set("", GetArena());
  }
  return released;
}
inline void C_Login::set_allocated_unique_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.unique_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.unique_id_.IsDefault()) {
    _impl_.unique_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:C_Login.unique_id)
}

// -------------------------------------------------------------------

// S_Login

// bool login_ok = 1;
inline void S_Login::clear_login_ok() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.login_ok_ = false;
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline bool S_Login::login_ok() const {
  // @@protoc_insertion_point(field_get:S_Login.login_ok)
  return _internal_login_ok();
}
inline void S_Login::set_login_ok(bool value) {
  _internal_set_login_ok(value);
  _impl_._has_bits_[0] |= 0x00000004U;
  // @@protoc_insertion_point(field_set:S_Login.login_ok)
}
inline bool S_Login::_internal_login_ok() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.login_ok_;
}
inline void S_Login::_internal_set_login_ok(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.login_ok_ = value;
}

// uint64 player_id = 2;
inline void S_Login::clear_player_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.player_id_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline ::uint64_t S_Login::player_id() const {
  // @@protoc_insertion_point(field_get:S_Login.player_id)
  return _internal_player_id();
}
inline void S_Login::set_player_id(::uint64_t value) {
  _internal_set_player_id(value);
  _impl_._has_bits_[0] |= 0x00000002U;
  // @@protoc_insertion_point(field_set:S_Login.player_id)
}
inline ::uint64_t S_Login::_internal_player_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.player_id_;
}
inline void S_Login::_internal_set_player_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.player_id_ = value;
}

// string nickname = 3;
inline void S_Login::clear_nickname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nickname_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& S_Login::nickname() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:S_Login.nickname)
  return _internal_nickname();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void S_Login::set_nickname(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.nickname_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:S_Login.nickname)
}
inline ::std::string* PROTOBUF_NONNULL S_Login::mutable_nickname()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_nickname();
  // @@protoc_insertion_point(field_mutable:S_Login.nickname)
  return _s;
}
inline const ::std::string& S_Login::_internal_nickname() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nickname_.Get();
}
inline void S_Login::_internal_set_nickname(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.nickname_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL S_Login::_internal_mutable_nickname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.nickname_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE S_Login::release_nickname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:S_Login.nickname)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.nickname_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.nickname_.Set("", GetArena());
  }
  return released;
}
inline void S_Login::set_allocated_nickname(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.nickname_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.nickname_.IsDefault()) {
    _impl_.nickname_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:S_Login.nickname)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::PacketId> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::PacketId>() {
  return ::PacketId_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Protocol_2eproto_2epb_2eh
